### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by hemajv**
cc @Shreyanand

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@harshad16 @tumido should shesheta merge this now as well?

**Comment by harshad16** [comment]
yes, we should. 
once this passes into merge pool
https://prow.operate-first.cloud/pr?query=is%3Apr%20repo%3Aopen-services-group%2Fmetrics%20author%3Ahemajv%20head%3Aupdate-owners

**Pull request merged**
