### PR TITLE
Store superset dashboard jsons

### LINKED ISSUE #35: Store Superset dashboard as json
With the recent PSI outage (https://github.com/operate-first/operations/issues/416), we lost our Superset dashboards/tables. We should save a backup of our dashboard and have the JSON updated in the repo.

### PR DESCRIPTION
**Pull request by hemajv**
Resolves #35

### CODE REVIEW

**Comment by chauhankaranraj** [comment]
Small nit - since we have a `reports` directory, could we store the jsons in there? (like we do for [ai4ci dashboards](https://github.com/aicoe-aiops/ocp-ci-analysis/tree/ca2387252b79f46f84a0a300e3471d0198e04cf0/reports) currently)

Otherwise looks great! :rocket:

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm
/approve

**Comment by hemajv** [comment]
> Small nit - since we have a `reports` directory, could we store the jsons in there? (like we do for [ai4ci dashboards](https://github.com/aicoe-aiops/ocp-ci-analysis/tree/ca2387252b79f46f84a0a300e3471d0198e04cf0/reports) currently)
> 
> Otherwise looks great! rocket

@chauhankaranraj good idea, Ill move it into the reports dir :+1:

**Review by suppathak — COMMENTED** [review]
/lgtm

**Review by Shreyanand — COMMENTED** [review]
The dashboards for viewing are available [here](https://superset.operate-first.cloud/superset/dashboard/1/) and [here](https://superset.operate-first.cloud/superset/dashboard/2/). 
/approve

**Pull request merged**
