### PR TITLE
Add contributors table

### PR DESCRIPTION
**Pull request by Shreyanand**
For issue #22, this PR fetches events from repositories, extracts contributor information from them and adds a table to Trino for visualization. 
Also, it updates the pipfile with required dependencies.

Co-authored-by: Hema Veeradhi <hveeradh@redhat.com>
Co-authored-by: Karanraj Chauhan <kachau@redhat.com>

### CODE REVIEW

**Review by oindrillac — APPROVED** [review]
/lgtm

**Comment by Shreyanand** [comment]
Seems like this module is not available to the pre-commit environment ([source](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/open-services-group_metrics/25/pre-commit/1502270541325668352#1:build-log.txt%3A85)).
@harshad16 any idea why that's happening?

**Comment by harshad16** [comment]
> Seems like this module is not available to the pre-commit environment ([source](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/open-services-group_metrics/25/pre-commit/1502270541325668352#1:build-log.txt%3A85)). 

@Shreyanand seems like the module not available issue is already fixed:
https://github.com/s-weigand/flake8-nb/issues/206

**Comment by Shreyanand** [comment]
@harshad16 thanks, it seems it's fixed but I tried to `pre-commit clea` and then initialize the environment again and saw another error:
Screenshot from 2022-03-15 15-23-48
Is this known?

**Comment by harshad16** [comment]
@Shreyanand please check all ssh url to htps URL 
https://github.com/open-services-group/metrics/blob/848facde23ee824f1a598a0efded1a9f7268d21c/.pre-commit-config.yaml#L3
to fix that authentication issue.

**Comment by Shreyanand** [comment]
> @Shreyanand please check all ssh url to htps URL
> 
> https://github.com/open-services-group/metrics/blob/848facde23ee824f1a598a0efded1a9f7268d21c/.pre-commit-config.yaml#L3
> 
> 
> to fix that authentication issue.

Thanks, that fixed it :+1: 
Does this mean other repos .pre-commit-config.yaml has to change?

**Comment by harshad16** [comment]
@Shreyanand 
yes, I had sent a note on this long ago.
here is the issue: https://github.com/thoth-station/thoth-application/issues/2111
update your repo based on your convenience.

**Comment by Shreyanand** [comment]
> @Shreyanand yes, I had sent a note on this long ago. here is the issue: [thoth-station/thoth-application#2111](https://github.com/thoth-station/thoth-application/issues/2111) update your repo based on your convenience.

Thanks this is helpful, added an [issue](https://github.com/aicoe-aiops/project-template/issues/55) in the project template for future projects using it.

**Pull request merged**
